spring:
  mail:
    host: smtp.126.com
    username: wwggyy_2@126.com
    password: wgy8865461
    default-encoding: UTF-8
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    virtual-host: /order
    connection-timeout: 15000
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
#  datasource:
#    url: jdbc:mysql://localhost:3306/order?characterEncoding=UTF-8
#    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://120.79.208.188:8761/eureka
server:
  port: 8083
  servlet:
    context-path: /
logging:
  level:
    com:
      valor:
        practice:
          mapper:
            DEBUG