package com.valor.practice.learn;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-08-29T14:50:54.421+08:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "CommJiraData",
                  wsdlLocation = "http://10.202.6.70:6060/itdd-app/inf-ws/CommJiraData?wsdl",
                  targetNamespace = "http://impl.server.itms.inf.itdd.sf.com/")
public class CommJiraData extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.server.itms.inf.itdd.sf.com/", "CommJiraData");
    public final static QName CommJiraServiceImplPort = new QName("http://impl.server.itms.inf.itdd.sf.com/", "CommJiraServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.202.6.70:6060/itdd-app/inf-ws/CommJiraData?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CommJiraData.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.202.6.70:6060/itdd-app/inf-ws/CommJiraData?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CommJiraData(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CommJiraData(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommJiraData() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CommJiraData(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CommJiraData(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CommJiraData(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ICommJiraService
     */
    @WebEndpoint(name = "CommJiraServiceImplPort")
    public ICommJiraService getCommJiraServiceImplPort() {
        return super.getPort(CommJiraServiceImplPort, ICommJiraService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICommJiraService
     */
    @WebEndpoint(name = "CommJiraServiceImplPort")
    public ICommJiraService getCommJiraServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CommJiraServiceImplPort, ICommJiraService.class, features);
    }

}
