package com.valor.practice.learn;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-08-29T14:50:54.385+08:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://server.itms.inf.itdd.sf.com/", name = "ICommJiraService")
@XmlSeeAlso({ObjectFactory.class})
public interface ICommJiraService {

//    @WebMethod
//    @RequestWrapper(localName = "getLabels", targetNamespace = "http://server.itms.inf.itdd.sf.com/", className = "com.sf.itdd.inf.itms.server.GetLabels")
//    @ResponseWrapper(localName = "getLabelsResponse", targetNamespace = "http://server.itms.inf.itdd.sf.com/", className = "com.sf.itdd.inf.itms.server.GetLabelsResponse")
//    @WebResult(name = "return", targetNamespace = "")
//    public java.lang.String getLabels(
//
//        @WebParam(name = "query", targetNamespace = "")
//        java.lang.String query
//    );

    @WebMethod
    @RequestWrapper(localName = "uploadIssueAttachments", targetNamespace = "http://server.itms.inf.itdd.sf.com/", className = "com.sf.itdd.inf.itms.server.UploadIssueAttachments")
    @ResponseWrapper(localName = "uploadIssueAttachmentsResponse", targetNamespace = "http://server.itms.inf.itdd.sf.com/", className = "com.sf.itdd.inf.itms.server.UploadIssueAttachmentsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean uploadIssueAttachments(

        @WebParam(name = "issueIdOrKey", targetNamespace = "")
        java.lang.String issueIdOrKey,
        @WebParam(name = "files", targetNamespace = "")
        java.util.List<com.valor.practice.learn.CxfFileHandler> files
    );

//    @WebMethod
//    @RequestWrapper(localName = "createIterDefect", targetNamespace = "http://server.itms.inf.itdd.sf.com/", className = "com.sf.itdd.inf.itms.server.CreateIterDefect")
//    @ResponseWrapper(localName = "createIterDefectResponse", targetNamespace = "http://server.itms.inf.itdd.sf.com/", className = "com.sf.itdd.inf.itms.server.CreateIterDefectResponse")
//    @WebResult(name = "return", targetNamespace = "")
//    public com.sf.itdd.inf.itms.server.SyncJIRADataResult createIterDefect(
//
//        @WebParam(name = "defectInfo", targetNamespace = "")
//        java.lang.String defectInfo
//    );
//
//    @WebMethod
//    @RequestWrapper(localName = "querySysReqsBySystemCode", targetNamespace = "http://server.itms.inf.itdd.sf.com/", className = "com.sf.itdd.inf.itms.server.QuerySysReqsBySystemCode")
//    @ResponseWrapper(localName = "querySysReqsBySystemCodeResponse", targetNamespace = "http://server.itms.inf.itdd.sf.com/", className = "com.sf.itdd.inf.itms.server.QuerySysReqsBySystemCodeResponse")
//    @WebResult(name = "return", targetNamespace = "")
//    public java.lang.String querySysReqsBySystemCode(
//
//        @WebParam(name = "sysCode", targetNamespace = "")
//        java.lang.String sysCode
//    );
//
//    @WebMethod
//    @RequestWrapper(localName = "getIterDefectsBySyscodeAndVersion", targetNamespace = "http://server.itms.inf.itdd.sf.com/", className = "com.sf.itdd.inf.itms.server.GetIterDefectsBySyscodeAndVersion")
//    @ResponseWrapper(localName = "getIterDefectsBySyscodeAndVersionResponse", targetNamespace = "http://server.itms.inf.itdd.sf.com/", className = "com.sf.itdd.inf.itms.server.GetIterDefectsBySyscodeAndVersionResponse")
//    @WebResult(name = "return", targetNamespace = "")
//    public com.sf.itdd.inf.itms.server.SyncJIRADataResult getIterDefectsBySyscodeAndVersion(
//
//        @WebParam(name = "info", targetNamespace = "")
//        java.lang.String info
//    );
}
